import Scheme from '../models/Scheme.js'

const sampleSchemes = [
  {
    name: 'PM Scholarship Scheme',
    type: 'education',
    category: 'All',
    state: 'All',
    incomeLimit: 250000,
    benefits: 'Financial support',
    eligibility: 'Income <= 2.5L',
    link: '#',
  },
  {
    name: 'National Means-cum-Merit Scholarship',
    type: 'education',
    category: 'All',
    state: 'All',
    incomeLimit: 350000,
    benefits: 'Scholarship for students',
    eligibility: 'Merit + income criteria',
    link: '#',
  },
  {
    name: 'Post Matric Scholarship (SC)',
    type: 'education',
    category: 'SC',
    state: 'All',
    incomeLimit: 250000,
    benefits: 'Tuition + maintenance allowance',
    eligibility: 'SC students in post-matric courses',
    link: '#',
  },
  {
    name: 'Post Matric Scholarship (ST)',
    type: 'education',
    category: 'ST',
    state: 'All',
    incomeLimit: 250000,
    benefits: 'Tuition + maintenance allowance',
    eligibility: 'ST students in post-matric courses',
    link: '#',
  },
  {
    name: 'OBC Education Assistance',
    type: 'education',
    category: 'OBC',
    state: 'All',
    incomeLimit: 200000,
    benefits: 'Education financial assistance',
    eligibility: 'OBC students meeting income criteria',
    link: '#',
  },
  {
    name: 'Women Entrepreneurship Support',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 800000,
    benefits: 'Training + low-interest loans',
    eligibility: 'Women entrepreneurs',
    link: '#',
  },
  {
    name: 'Farmer Equipment Subsidy (Maharashtra)',
    type: 'agriculture',
    category: 'All',
    state: 'Maharashtra',
    incomeLimit: 600000,
    benefits: 'Subsidy on farm equipment',
    eligibility: 'Farmers in Maharashtra',
    link: '#',
  },
  {
    name: 'Student Fee Reimbursement (Delhi)',
    type: 'education',
    category: 'All',
    state: 'Delhi',
    incomeLimit: 300000,
    benefits: 'Fee reimbursement',
    eligibility: 'Residents of Delhi meeting criteria',
    link: '#',
  },
  {
    name: 'Skill Development Stipend',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 400000,
    benefits: 'Monthly stipend during training',
    eligibility: 'Eligible trainees in approved programs',
    link: '#',
  },
  {
    name: 'Healthcare Assistance for BPL',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 200000,
    benefits: 'Coverage for select medical procedures',
    eligibility: 'Income-based eligibility',
    link: '#',
  },
  {
    name: 'Hostel Support (SC/ST) - Karnataka',
    type: 'education',
    category: 'SC',
    state: 'Karnataka',
    incomeLimit: 250000,
    benefits: 'Hostel fee support',
    eligibility: 'SC students in Karnataka',
    link: '#',
  },

  // ── New Schemes ──────────────────────────────────────────────────
  {
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 1000000,
    benefits: '₹6,000/year direct income support in 3 instalments',
    eligibility: 'Small and marginal farmers owning cultivable land',
    link: '#',
  },
  {
    name: 'Kisan Credit Card Scheme',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 1200000,
    benefits: 'Credit up to ₹3 lakh at subsidised interest rate',
    eligibility: 'Farmers, fishers, animal husbandry workers',
    link: '#',
  },
  {
    name: 'Pradhan Mantri Fasal Bima Yojana',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 1500000,
    benefits: 'Crop insurance coverage at low premium',
    eligibility: 'Farmers with crop loss due to natural calamities',
    link: '#',
  },
  {
    name: 'Soil Health Card Scheme',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 2000000,
    benefits: 'Free soil testing + nutrient recommendations',
    eligibility: 'All farmers with agricultural land',
    link: '#',
  },
  {
    name: 'Micro Irrigation Fund',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 800000,
    benefits: 'Subsidy on drip and sprinkler irrigation systems',
    eligibility: 'Farmers adopting micro-irrigation',
    link: '#',
  },
  {
    name: 'Pradhan Mantri Awas Yojana (Urban)',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 600000,
    benefits: 'Subsidy up to ₹2.67 lakh on home loan',
    eligibility: 'EWS/LIG families without pucca house',
    link: '#',
  },
  {
    name: 'MUDRA Loan – Shishu',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 1000000,
    benefits: 'Collateral-free loan up to ₹50,000 for micro-businesses',
    eligibility: 'Small businesses and startups',
    link: '#',
  },
  {
    name: 'MUDRA Loan – Kishore',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 1200000,
    benefits: 'Loan from ₹50,000 to ₹5 lakh for business expansion',
    eligibility: 'Established micro and small businesses',
    link: '#',
  },
  {
    name: 'PM Employment Generation Programme',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 1500000,
    benefits: 'Subsidy 15–35% on project cost for self-employment',
    eligibility: 'Individuals above 18 with 8th-grade education',
    link: '#',
  },
  {
    name: 'Startup India Seed Fund',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 5000000,
    benefits: 'Seed funding up to ₹20 lakh for early-stage startups',
    eligibility: 'DPIIT-recognised startups < 2 years old',
    link: '#',
  },
  {
    name: 'PM Vishwakarma Yojana',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 500000,
    benefits: '₹15,000 toolkit grant + ₹1–2 lakh collateral-free loan',
    eligibility: 'Traditional artisans and craftspeople',
    link: '#',
  },
  {
    name: 'Begum Hazrat Mahal Scholarship (Minority Girls)',
    type: 'education',
    category: 'All',
    state: 'All',
    incomeLimit: 200000,
    benefits: '₹5,000–₹6,000 annual scholarship',
    eligibility: 'Minority community girls in class 9–12',
    link: '#',
  },
  {
    name: 'National Fellowship for SC Students',
    type: 'education',
    category: 'SC',
    state: 'All',
    incomeLimit: 800000,
    benefits: 'JRF/SRF fellowship for M.Phil/PhD scholars',
    eligibility: 'SC students pursuing higher research',
    link: '#',
  },
  {
    name: 'Ishan Uday Scholarship (NE States)',
    type: 'education',
    category: 'All',
    state: 'All',
    incomeLimit: 450000,
    benefits: '₹5,400–₹7,800/month scholarship',
    eligibility: 'Students from North-East states in general/professional courses',
    link: '#',
  },
  {
    name: 'Central Sector Scholarship (Higher Education)',
    type: 'education',
    category: 'All',
    state: 'All',
    incomeLimit: 450000,
    benefits: '₹10,000–₹20,000 per year for college students',
    eligibility: 'Top 20 percentile in 12th board + income criteria',
    link: '#',
  },
  {
    name: 'Driving Training Scheme (SC/ST)',
    type: 'jobs',
    category: 'SC',
    state: 'All',
    incomeLimit: 300000,
    benefits: 'Free driving training + subsidy on vehicle purchase',
    eligibility: 'SC/ST candidates seeking self-employment',
    link: '#',
  },
  {
    name: 'Stand-Up India',
    type: 'jobs',
    category: 'SC',
    state: 'All',
    incomeLimit: 10000000,
    benefits: 'Bank loans ₹10 lakh–₹1 crore for greenfield enterprises',
    eligibility: 'SC/ST or women entrepreneurs',
    link: '#',
  },
  {
    name: 'Pmegp Minority Artisan Scheme',
    type: 'jobs',
    category: 'OBC',
    state: 'All',
    incomeLimit: 600000,
    benefits: 'Grant + training for traditional craftspersons',
    eligibility: 'Minority/OBC artisans in cottage industries',
    link: '#',
  },
  {
    name: 'Aam Aadmi Bima Yojana',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 300000,
    benefits: 'Life + disability insurance cover',
    eligibility: 'BPL families, landless agricultural labourers',
    link: '#',
  },
  {
    name: 'Ayushman Bharat – PMJAY',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 300000,
    benefits: 'Health cover up to ₹5 lakh/year per family',
    eligibility: 'Vulnerable/deprived families as per SECC data',
    link: '#',
  },
  {
    name: 'Janani Suraksha Yojana',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 250000,
    benefits: 'Cash assistance for institutional delivery',
    eligibility: 'Pregnant BPL women above 19 years',
    link: '#',
  },
  {
    name: 'Rashtriya Swasthya Bima Yojana',
    type: 'jobs',
    category: 'All',
    state: 'All',
    incomeLimit: 200000,
    benefits: 'Cashless hospitalisation up to ₹30,000/year',
    eligibility: 'BPL families in unorganised sector',
    link: '#',
  },
  {
    name: 'National Agriculture Market (e-NAM)',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 2000000,
    benefits: 'Online trading platform access + better price discovery',
    eligibility: 'Farmers registered with APMC mandis',
    link: '#',
  },
  {
    name: 'Rashtriya Krishi Vikas Yojana',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 2000000,
    benefits: 'Grants for agricultural infrastructure and technology',
    eligibility: 'Farmers and farmer cooperatives',
    link: '#',
  },
  {
    name: 'Paramparagat Krishi Vikas Yojana',
    type: 'agriculture',
    category: 'All',
    state: 'All',
    incomeLimit: 1000000,
    benefits: '₹50,000/hectare for organic farming over 3 years',
    eligibility: 'Farmers transitioning to certified organic farming',
    link: '#',
  },
]

async function seedSchemesIfEmpty() {
  const count = await Scheme.estimatedDocumentCount()
  if (count > 0) return { inserted: 0, skipped: true }

  await Scheme.insertMany(sampleSchemes)
  return { inserted: sampleSchemes.length, skipped: false }
}

export { seedSchemesIfEmpty }

